// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nox.Reference;

#nullable disable

namespace Nox.Reference.Data.Machine.Migrations
{
    [DbContext(typeof(MachineDbContext))]
    partial class MachineDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("Nox.Reference.MacAddress", b =>
                {
                    b.Property<int>("EntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("IEEERegistry")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MacPrefix")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OrganizationAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EntityId");

                    b.ToTable("MacAddress");
                });
#pragma warning restore 612, 618
        }
    }
}
