using System.Text.Json.Serialization;

namespace Nox.Reference;

[JsonConverter(typeof(JsonStringEnumConverter))]
public enum ChecksumAlgorithm
{
    None,
    Luhn,
    Mod,
    ModAndSubstract,
    ModAndSubstract_IT,
    MX_Algorithm,
    DE_Algorithm,
    FR_Algorithm,
    CO_Algorithm,
    AU_Algorithm,
    BE_Algorithm,
    BR_Algorithm,
    CA_Algorithm,
    CH_Algorithm,
    GB_Algorithm,
    ES_Algorithm1,
    ES_Algorithm2,
    ES_Algorithm3,
    DK_Algorithm,
    AT_Algorithm,
    JP_Algorithm,
    CN_Algorithm,
    TR_Algorithm,
    SE_Algorithm,
    NO_Algorithm,
    RU_Algorithm,
    NZ_Algorithm,
    ID_Algorithm,

   // TODO: split vat and tax
    CH_Tax_Algorithm,
    BR_Tax_Algorithm,
    IT_Tax_Algorithm,
    DE_Tax_Algorithm,
    NL_Tax_Algorithm,
    MX_Tax1_Algorithm,
    MX_Tax2_Algorithm,
    IN_Tax_Algorithm,
    CA_Tax_Algorithm,
    BE_Tax_Algorithm,
    AU_Tax_Algorithm,
    PL_Tax_Algorithm,
    DK_Tax_Algorithm,
    AT_Tax_Algorithm,
    TR_Tax_Algorithm,
    SE_Tax_Algorithm,
    IL_Tax_Algorithm,
    NO_Tax_Algorithm,
    NZ_Tax_Algorithm,
    FI_Tax_Algorithm,
}