name: Build & Test

on:
  pull_request:
    branches: [ main ]
    paths:
      - src/Nox.Reference.Abstractions/**
      - src/Nox.Reference.Countries/**
      - tests/Nox.Reference.Countries.Tests/**
      - .github/workflows/nox.reference.countries.ci.yaml
  push:
    branches: [ main ]
    paths:
      - src/Nox.Reference.Abstractions/**
      - src/Nox.Reference.Countries/**
      - tests/Nox.Reference.Countries.Tests/**
      - .github/workflows/nox.reference.countries.ci.yaml

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['6.0.x']

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Restore
        run: dotnet restore ./src/Nox.Reference.Countries/Nox.Reference.Countries.csproj
      - name: Build
        run: dotnet build ./src/Nox.Reference.Countries/Nox.Reference.Countries.csproj --warnaserror --configuration Release --no-restore      
      - name: Tests
        run: dotnet test ./tests/Nox.Reference.Countries.Tests/Nox.Reference.Countries.Tests.csproj --no-restore --verbosity minimal --configuration Release