name: Build & Test

on:
  pull_request:
    branches: [ main ]
    paths:
      - src/Nox.Reference.Common/**
      - tests/Nox.Reference.Common.Tests/**
      - .github/workflows/nox.reference.common.ci.yaml
  push:
    branches: [ main ]
    paths:
      - src/Nox.Reference.Common/**
      - tests/Nox.Reference.Common.Tests/**
      - .github/workflows/nox.reference.common.ci.yaml

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['6.0.x']

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Restore
        run: dotnet restore ./src/Nox.Reference.Common/Nox.Reference.Common.csproj
      - name: Build
        run: dotnet build ./src/Nox.Reference.Common/Nox.Reference.Common.csproj --warnaserror --configuration Release --no-restore